backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "clothes"
    label: "Ρούχα Μπουτίκ"
    folder: "content/clothes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Τίτλος Προϊόντος", name: "title", widget: "string", hint: "Γράψε το όνομα του ρούχου"}
      - {label: "Κατηγορία", name: "category", widget: "select", options: ["Φορέματα", "Παντελόνια", "Casual Chic", "Βραδινά"], hint: "Διάλεξε κατηγορία"}
      - {label: "Περιγραφή", name: "description", widget: "text"}
      - {label: "Τιμή (€)", name: "price", widget: "number", value_type: "int"}
      - {label: "Φωτογραφία", name: "image", widget: "image"}
